version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: ember-cli
    versions:
    - ">= 0"
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.1
    - 3.25.3
    - 3.26.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.0
    - 2.0.1
